export const trendingLyrics = [
  {
    id: "1",
    title: "Song of Fury",
    artist: "The Thunder",
    album: "Storm Rises",
    genre: ["Metal", "Rock"],
    releaseDate: "2023-01-15T00:00:00Z",
    duration: "4:20",
    lyrics: "Lyrics of Song of Fury...",
    mainIdea: "The power of nature",
    description: "A powerful song about the forces of nature.",
    ranking: 1,
    thumbnailUrl: "https://example.com/path/to/thumbnail1.jpg",
    audioUrl: "https://example.com/path/to/audio1.mp3",
  },
  {
    id: "2",
    title: "Echoes in Silence",
    artist: "Whispers of Doom",
    album: "Silent Nightmares",
    genre: ["Metal", "Gothic"],
    releaseDate: "2023-05-22T00:00:00Z",
    duration: "5:35",
    lyrics: "Lyrics of Echoes in Silence...",
    mainIdea: "Inner battles",
    description: "A haunting melody about internal struggles.",
    ranking: 2,
    thumbnailUrl: "https://example.com/path/to/thumbnail2.jpg",
    audioUrl: "https://example.com/path/to/audio2.mp3",
  },
  {
    id: "3",
    title: "Dark Horizons",
    artist: "Blackened Skies",
    album: "Nightfall",
    genre: ["Metal", "Symphonic"],
    releaseDate: "2023-09-10T00:00:00Z",
    duration: "3:45",
    lyrics: "Lyrics of Dark Horizons...",
    mainIdea: "Embracing the unknown",
    description: "An epic symphony about venturing into the unknown.",
    ranking: 3,
    thumbnailUrl: "https://example.com/path/to/thumbnail3.jpg",
    audioUrl: "https://example.com/path/to/audio3.mp3",
  },
  // Add more lyrics data here
];
