export const normalLyrics = [
  {
    id: "1",
    title: "Whispers in the Dark",
    artist: "Echoes of Eternity",
    album: "Nightfall",
    genre: ["Metal", "Gothic"],
    releaseDate: "2023-02-10T00:00:00Z",
    duration: "5:00",
    lyrics: "Lyrics of Whispers in the Dark...",
    mainIdea: "Darkness and mystery",
    description: "A deep dive into the themes of darkness and mystery.",
    thumbnailUrl: "https://example.com/path/to/thumbnail1.jpg",
    audioUrl: "https://example.com/path/to/audio1.mp3",
  },
  {
    id: "2",
    title: "Rise of the Fallen",
    artist: "Abyssal Depths",
    album: "Descent",
    genre: ["Metal", "Symphonic"],
    releaseDate: "2023-06-18T00:00:00Z",
    duration: "4:30",
    lyrics: "Lyrics of Rise of the Fallen...",
    mainIdea: "Resilience",
    description: "A powerful anthem about resilience and rising again.",
    thumbnailUrl: "https://example.com/path/to/thumbnail2.jpg",
    audioUrl: "https://example.com/path/to/audio2.mp3",
  },
  {
    id: "3",
    title: "Into the Void",
    artist: "Voidwalker",
    album: "Journey Beyond",
    genre: ["Metal", "Progressive"],
    releaseDate: "2023-09-25T00:00:00Z",
    duration: "6:15",
    lyrics: "Lyrics of Into the Void...",
    mainIdea: "Exploration of the unknown",
    description: "An epic track about venturing into the unknown.",
    thumbnailUrl: "https://example.com/path/to/thumbnail3.jpg",
    audioUrl: "https://example.com/path/to/audio3.mp3",
  },
  // Add more lyrics data here
];
